### ISSUE TITLE
Are you able to release the prompts for the images?

### ISSUE THREAD

**Issue by amitkparekh** [isekai-portal/Link-Context-Learning#1]
The images are really cool. Are you able to release the prompts used to generate the images in Midjourney?

**Comment by WeichenFan** [comment]
Thanks for your interest.

Yes, we are planning to release the prompts used to generate images after we release the whole dataset.

**Comment by piligoing** [comment]
> Thanks for your interest.
> 
> Yes, we are planning to release the prompts used to generate images after we release the whole dataset.

wonderful job! Kindly, can you publish the prompt that generates these pictures? Thank you so much 🙏
