### ISSUE TITLE
Would you mind release the evaluation code？

### ISSUE THREAD

**Issue by Darren-greenhand** [isekai-portal/Link-Context-Learning#3]
Hi! thx for your great work! 🥂 
We want to test our model on your ISEKAI Dataset but I can't find more details in the paper
Would you please release the evaluation code you use? 😄

**Comment by MacavityT** [comment]
Thank you for your attention. We are currently organizing the code and will open-source all contents, including training and evaluating code, checkpoints, dataset, etc., within the next few days. Please stay tuned.😊
