### ISSUE TITLE
Question about in-context examples

### ISSUE THREAD

**Issue by gray311** [isekai-portal/Link-Context-Learning#4]
Can you tell me how the in-context examples for otter and openflamingo are selected in ISEKAI-10 Evaluation? Is it only from the 16 negative examples? Or are positive and negative examples picked one at a time (2-shots, 4-shots...).

**Comment by MacavityT** [comment]
We choose positive-and-negative pairs for otter, flamingo, and our lcl model. For example, if we intend to perform inference on an image (like icemic, etc.), we input 1 ice cream and 1 icemic image in a 2-shot lcl setting (icemic serves as the positive sample, and ice cream as the negative sample). You can check the setting by downloading our ISEKAI dataset. Moreover, we will release our training and evaluation code, along with our 2-way-weight checkpoint. Thank you for your attention
