### ISSUE TITLE
About evaluations in your paper.

### ISSUE THREAD

**Issue by osttkm** [isekai-portal/Link-Context-Learning#6]
Hi! thanks for your great work! 
I hava a question about experiments in your paper.

Regarding the experiments in Table 1 and Table 2, was the Otter model evaluated using the weights trained on the MIMIC-IT dataset? Or was it evaluated using weights that were additionally trained on a dataset like Imagenet? Please let me know.

**Comment by MacavityT** [comment]
Thanks for your attention, we used the weight from [Oringin Weight](https://huggingface.co/luodian/OTTER-Image-LLaMA7B-LA-InContext), without any extra tunning.
