### ISSUE TITLE
Something wrong with demo

### ISSUE THREAD

**Issue by CleyLyChen** [isekai-portal/Link-Context-Learning#9]
Hi! Great Work!
I want to play with your demo with some simple toy case, but it seems something wrong with your demo website, are you going to fix it in recent days?

**Comment by WeichenFan** [comment]
Hi, thanks for your interest! The original demo is hosted on Sensetime's server, but we are no longer able to support it as none of the authors are currently working at Sensetime. You might consider hosting the demo locally instead.
